apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "diaggarwtest-620e"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "diaggarwtest-620e"
    spec:
      containers:
        - name: "diaggarwtest-620e"
          image: "diaggaw.azurecr.io/diaggarwtest"
          ports:
          - containerPort: 8080